### ISSUE TITLE
f.start.me无法识别部分网站的favicon

### ISSUE THREAD

**Issue by xbpk3t** [x1ah/gena#10]
在使用过程中发现，目前使用的 [f.start.me](https://f.start.me/) 无法识别部分网站的favicon

- [opensource.builders (256×256)](https://f.start.me/opensource.builders)
- [rsshub](https://f.start.me/docs.rsshub.app/social-media.html#bilibili)

发现使用 [splitbee/favicon-resolver](https://github.com/splitbee/favicon-resolver) 提供的favicon识别功能，可以解决这个问题

- [favicon.splitbee.io (32×32)](https://favicon.splitbee.io/?url=opensource.builders)
- [rsshub](https://favicon.splitbee.io/?url=docs.rsshub.app/social-media.html#bilibili)

能否使用favicon-resolver替换f.start.me呢？

**Comment by x1ah** [comment]
@hapihacking f.start.me 是 start.me 提供的能力，服务比较靠谱，访问也比较快，可能只是小部分网站没解析出来，大部分网站解析体验还是比较好的，暂时不考虑替换哈。对于没解析出来的你可以自己配置图标，有一个 icon 的 key
![image](https://user-images.githubusercontent.com/14919255/230760530-2fd2262f-13ab-4227-8afa-752844aa1a41.png)

**Comment by xbpk3t** [comment]
好的，谢谢回复
