### ISSUE TITLE
能否添加一个remark备注字段，在页面上不展示，仅供自己添加更多备注信息

### ISSUE THREAD

**Issue by xbpk3t** [x1ah/gena#9]

**Comment by x1ah** [comment]
@luckyhacking 可以直接写注释，是这种吧？
<img width="568" alt="image" src="https://user-images.githubusercontent.com/14919255/212890380-804d9af9-2379-4582-b0e6-987afbb5ec13.png">

**Comment by xbpk3t** [comment]
类似每个网站的description参数，但是页面上不展示的

**Comment by x1ah** [comment]
@luckyhacking 页面上不展示那和注释有什么区别？

**Comment by xbpk3t** [comment]
我先用注释实现这个需求吧，感觉大部分人是不需要这个的
